from fpdf import FPDF
import datetime

def clean_pdf_text(text):
    """FIX: Replaces unsupported characters to prevent 'latin-1' encoding crashes."""
    if not isinstance(text, str):
        return str(text)
        
    replacements = {
        '\u2014': '-', '\u2013': '-',   # Em and En dashes
        '\u2018': "'", '\u2019': "'",   # Smart single quotes
        '\u201c': '"', '\u201d': '"',   # Smart double quotes
        '\u2022': '-', '\t': '    '     # Bullets and tabs
    }
    for bad_char, good_char in replacements.items():
        text = text.replace(bad_char, good_char)
        
    # Ignore any remaining strange characters to ensure the PDF always generates
    return text.encode('latin-1', 'ignore').decode('latin-1')

def generate_pdf_report(results, role, grammar_errors=None, jd_score=0.0):
    """Generates a categorized, professional PDF summary of the analysis"""
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt=clean_pdf_text("PrepMate: Advanced Resume Analysis Report"), ln=True, align='C')
    pdf.set_font("Arial", size=10)
    pdf.cell(200, 10, txt=clean_pdf_text(f"Date: {datetime.date.today()}"), ln=True, align='C')
    pdf.ln(10)

    # Score Section
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt=clean_pdf_text(f"Target Role: {role.replace('_', ' ')}"), ln=True)
    pdf.set_text_color(0, 128, 0) # Green for score
    pdf.cell(200, 10, txt=clean_pdf_text(f"Overall Match Score: {jd_score}%"), ln=True)
    pdf.set_text_color(0, 0, 0) # Back to black
    pdf.ln(10)

    # Categorized Skills Section
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt=clean_pdf_text("1. Skill Breakdown by Category"), ln=True)
    pdf.ln(2)

    detailed_stats = results.get("detailed", {})
    
    for category, stats in detailed_stats.items():
        # Category Header (e.g., "Programming Languages")
        pdf.set_font("Arial", 'B', 12)
        pdf.set_text_color(0, 51, 102) # Dark Blue
        pdf.cell(200, 8, txt=clean_pdf_text(f"[{category}]"), ln=True)
        pdf.set_text_color(0, 0, 0)
        
        # Found Skills
        pdf.set_font("Arial", 'I', 10)
        pdf.cell(30, 6, txt="Found:", border=0)
        pdf.set_font("Arial", '', 10)
        found_text = ", ".join(stats['found']) if stats['found'] else "None"
        pdf.multi_cell(0, 6, txt=clean_pdf_text(found_text))
        
        # Missing Skills
        pdf.set_font("Arial", 'I', 10)
        pdf.set_text_color(200, 0, 0) # Red
        pdf.cell(30, 6, txt="Missing:", border=0)
        pdf.set_font("Arial", '', 10)
        missing_text = ", ".join(stats['missing']) if stats['missing'] else "None (Perfect!)"
        pdf.multi_cell(0, 6, txt=clean_pdf_text(missing_text))
        pdf.set_text_color(0, 0, 0)
        pdf.ln(4)

    # Grammar Section
    pdf.add_page() # Put grammar on a new page to keep it clean
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt=clean_pdf_text("2. Grammar & Professionalism Check"), ln=True)
    pdf.ln(5)

    if grammar_errors:
        for i, err in enumerate(grammar_errors, 1):
            pdf.set_font("Arial", 'B', 11)
            pdf.cell(200, 8, txt=clean_pdf_text(f"Issue {i}: {err['message']}"), ln=True)
            
            pdf.set_font("Arial", '', 10)
            pdf.set_text_color(100, 100, 100) # Gray
            pdf.multi_cell(0, 6, txt=clean_pdf_text(f"Context: \"...{err['context']}...\""))
            
            pdf.set_text_color(0, 128, 0) # Green
            pdf.cell(200, 6, txt=clean_pdf_text(f"Suggestion: Change to '{err['suggestion']}'"), ln=True)
            pdf.set_text_color(0, 0, 0)
            pdf.ln(4)
    else:
        pdf.set_font("Arial", '', 11)
        pdf.cell(200, 10, txt=clean_pdf_text("No major grammatical issues found. Great job!"), ln=True)

    # Footer
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 8)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 10, clean_pdf_text("Generated by PrepMate AI Interview Simulation Platform"), 0, 0, 'C')
    
    return pdf.output(dest='S').encode('latin-1')